### ISSUE TITLE
Air Mini+  - Loaded 0 cached accessories from 

### ISSUE THREAD

**Issue by jakubkasparek** [csirikak/homebridge-molekule#12]
my log:

11/9/2023, 10:09:34 AM] [homebridge-molekule] Launched child bridge with PID XXXX
[11/9/2023, 10:09:34 AM] Registering platform 'homebridge-molekule.Molekule'
[11/9/2023, 10:09:34 AM] [homebridge-molekule] Loaded homebridge-molekule v1.4.1 child bridge successfully
**[11/9/2023, 10:09:34 AM] Loaded 0 cached accessories from cachedAccessories.XXXXXX**
[11/9/2023, 10:09:35 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-molekule) is running on port 53252.
[11/9/2023, 10:09:37 AM] [homebridge-molekule] ✓ Valid Login Credentials

the purifier won't load.
Does this plugin work for anyone?

**Comment by csirikak** [comment]
Would you post your full log with homebridge debug mode turned on?

**Comment by jakubkasparek** [comment]
`[11/10/2023, 6:50:58 AM] ---
[11/10/2023, 6:50:58 AM] Loaded plugin: homebridge-molekule@1.4.1
[11/10/2023, 6:50:58 AM] Registering platform 'homebridge-molekule.Molekule'
[11/10/2023, 6:50:59 AM] ---
[11/10/2023, 6:50:59 AM] [homebridge-molekule] Initializing Molekule platform...
[11/10/2023, 6:50:59 AM] [homebridge-molekule] Initializing child bridge 0E:AA:98:A3:3B:35
[11/10/2023, 6:51:00 AM] [homebridge-molekule] Launched child bridge with PID 112472
[11/10/2023, 6:51:00 AM] Registering platform 'homebridge-molekule.Molekule'
[11/10/2023, 6:51:00 AM] [homebridge-molekule] Loaded homebridge-molekule v1.4.1 child bridge successfully
[11/10/2023, 6:51:01 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-molekule) is running on port 33354.
[11/10/2023, 6:51:04 AM] [homebridge-molekule] ✓ Valid Login Credentials
`

you mean this?

**Comment by jakubkasparek** [comment]
[11/10/2023, 6:59:51 AM] [homebridge-molekule] Restarting child bridge...
[11/10/2023, 6:59:51 AM] Got SIGTERM, shutting down child bridge process...
[11/10/2023, 6:59:56 AM] [homebridge-molekule] Child bridge process ended
[11/10/2023, 6:59:56 AM] [homebridge-molekule] Process Ended. Code: 143, Signal: null
[11/10/2023, 7:00:03 AM] [homebridge-molekule] Restarting Process...
2023-11-10T06:00:04.073Z ciao:init Loading ciao v1.1.7...
[11/10/2023, 7:00:04 AM] [homebridge-molekule] Launched child bridge with PID 113123
[11/10/2023, 7:00:04 AM] Registering platform 'homebridge-molekule.Molekule'
[11/10/2023, 7:00:04 AM] [homebridge-molekule] Loaded homebridge-molekule v1.4.1 child bridge successfully
[11/10/2023, 7:00:04 AM] Loaded 0 cached accessories from cachedAccessories.0EAA98A33B35.
[11/10/2023, 7:00:05 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-molekule) is running on port 33354.
[11/10/2023, 7:00:08 AM] [homebridge-molekule] ✓ Valid Login Credentials
[11/10/2023, 7:00:17 AM] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press

@csirikak you mean this?

**Comment by jakubkasparek** [comment]
@csirikak  sure

> [11/10/2023, 7:22:41 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 10DF) is running on port 52352.
> 2023-11-10T06:22:41.990Z ciao:init Loading ciao v1.1.7...
> 2023-11-10T06:22:42.414Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'REQUEST' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16)
> 2023-11-10T06:22:42.418Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'AUTHENTICATED' 	(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16)
> 2023-11-10T06:22:42.420Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'CLOSED' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16)
> 2023-11-10T06:22:42.421Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.176] New connection from client on interface eth0 (::ffff:192.168.1.176)
> 2023-11-10T06:22:42.423Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP server listening on 127.0.0.1:44337
> 2023-11-10T06:22:42.433Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.43] Registered event 'REQUEST' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16)
> 2023-11-10T06:22:42.435Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.43] Registered event 'AUTHENTICATED' 	(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16)
> 2023-11-10T06:22:42.437Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.43] Registered event 'CLOSED' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16)
> 2023-11-10T06:22:42.438Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.43] New connection from client on interface eth0 (::ffff:192.168.1.176)
> 2023-11-10T06:22:42.439Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] Internal HTTP server listening on 127.0.0.1:32833
> 2023-11-10T06:22:42.434Z HAP-NodeJS:Advertiser Initializing HAP-NodeJS v0.11.1 ...
> 2023-11-10T06:22:42.446Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP socket connected. HAPConnection now fully set up!
> 2023-11-10T06:22:42.450Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] Internal HTTP socket connected. HAPConnection now fully set up!
> 2023-11-10T06:22:42.455Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP request: /accessories
> 2023-11-10T06:22:42.456Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] HAP Request: GET /accessories
> 2023-11-10T06:22:42.478Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] HTTP request: /pair-verify
> 2023-11-10T06:22:42.479Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] HAP Request: POST /pair-verify
> 2023-11-10T06:22:42.482Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] Pair verify step 1/2
> 2023-11-10T06:22:42.603Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP Response is finished
> 2023-11-10T06:22:42.606Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] HTTP Response is finished
> 2023-11-10T06:22:42.609Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP connection was closed
> 2023-11-10T06:22:42.610Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:42.612Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Client connection closed
> 2023-11-10T06:22:42.613Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:42.628Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] HTTP request: /pair-verify
> 2023-11-10T06:22:42.629Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] HAP Request: POST /pair-verify
> 2023-11-10T06:22:42.630Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] Pair verify step 2/2
> 2023-11-10T06:22:42.719Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] Client 9FF50524-8161-41F7-A734-586ADDB8DEA0 verification complete
> 2023-11-10T06:22:42.741Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'REQUEST' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16)
> 2023-11-10T06:22:42.742Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'AUTHENTICATED' 	(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16)
> 2023-11-10T06:22:42.744Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'CLOSED' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16)
> 2023-11-10T06:22:42.744Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.176] New connection from client on interface eth0 (::ffff:192.168.1.176)
> 2023-11-10T06:22:42.746Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP server listening on 127.0.0.1:43061
> [11/10/2023, 7:22:42 AM] [homebridge-molekule] Launched child bridge with PID 114764
> 2023-11-10T06:22:42.751Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] HTTP Response is finished
> 2023-11-10T06:22:42.752Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP socket connected. HAPConnection now fully set up!
> 2023-11-10T06:22:42.754Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP request: /characteristics
> 2023-11-10T06:22:42.755Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] HAP Request: PUT /characteristics
> 2023-11-10T06:22:42.757Z HAP-NodeJS:Accessory [Homebridge 10DF 9364] Processing characteristic set: {"characteristics":[{"aid":-1,"iid":-1}]}
> 2023-11-10T06:22:42.759Z HAP-NodeJS:Accessory [Homebridge 10DF 9364] Could not find a Characteristic with aid of -1 and iid of -1
> 2023-11-10T06:22:42.762Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP Response is finished
> 2023-11-10T06:22:42.763Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP connection was closed
> 2023-11-10T06:22:42.764Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:42.765Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Client connection closed
> 2023-11-10T06:22:42.765Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:42.776Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] HTTP request: /accessories
> 2023-11-10T06:22:42.776Z HAP-NodeJS:HAPServer [0E:D7:F7:08:10:DF] HAP Request: GET /accessories
> 2023-11-10T06:22:42.782Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.43] HTTP Response is finished
> [11/10/2023, 7:22:42 AM] Registering platform 'homebridge-molekule.Molekule'
> [11/10/2023, 7:22:42 AM] [homebridge-molekule] Loaded homebridge-molekule v1.4.1 child bridge successfully
> [11/10/2023, 7:22:42 AM] Loaded 0 cached accessories from cachedAccessories.0EAA98A33B35.
> 2023-11-10T06:22:43.006Z HAP-NodeJS:Advertiser Preparing Advertiser for 'homebridge-molekule 07BA' using bonjour-hap backend!
> 2023-11-10T06:22:43.448Z HAP-NodeJS:EventedHTTPServer Server listening on [::]:33354
> 2023-11-10T06:22:43.450Z HAP-NodeJS:Advertiser Starting to advertise 'homebridge-molekule 07BA' using bonjour-hap backend!
> [11/10/2023, 7:22:43 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-molekule) is running on port 33354.
> 2023-11-10T06:22:44.536Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'REQUEST' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16)
> 2023-11-10T06:22:44.538Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'AUTHENTICATED' 	(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16)
> 2023-11-10T06:22:44.540Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'CLOSED' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16)
> 2023-11-10T06:22:44.541Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.176] New connection from client on interface eth0 (::ffff:192.168.1.176)
> 2023-11-10T06:22:44.544Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP server listening on 127.0.0.1:38717
> 2023-11-10T06:22:44.550Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP socket connected. HAPConnection now fully set up!
> 2023-11-10T06:22:44.555Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP request: /accessories
> 2023-11-10T06:22:44.556Z HAP-NodeJS:HAPServer [0E:AA:98:A3:3B:35] HAP Request: GET /accessories
> 2023-11-10T06:22:44.577Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP Response is finished
> 2023-11-10T06:22:44.580Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP connection was closed
> 2023-11-10T06:22:44.581Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:44.586Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'REQUEST' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:231:16)
> 2023-11-10T06:22:44.587Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'AUTHENTICATED' 	(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:234:16)
> 2023-11-10T06:22:44.589Z HAP-NodeJS:EventEmitter [::ffff:192.168.1.176] Registered event 'CLOSED' 		(total: 1) 		    at EventedHTTPServer.onConnection (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:235:16)
> 2023-11-10T06:22:44.589Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.176] New connection from client on interface eth0 (::ffff:192.168.1.176)
> 2023-11-10T06:22:44.590Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP server listening on 127.0.0.1:42371
> 2023-11-10T06:22:44.592Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Client connection closed
> 2023-11-10T06:22:44.594Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:44.596Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Internal HTTP socket connected. HAPConnection now fully set up!
> 2023-11-10T06:22:44.598Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP request: /characteristics
> 2023-11-10T06:22:44.598Z HAP-NodeJS:HAPServer [0E:AA:98:A3:3B:35] HAP Request: PUT /characteristics
> 2023-11-10T06:22:44.601Z HAP-NodeJS:Accessory [homebridge-molekule 07BA] Processing characteristic set: {"characteristics":[{"aid":-1,"iid":-1}]}
> 2023-11-10T06:22:44.603Z HAP-NodeJS:Accessory [homebridge-molekule 07BA] Could not find a Characteristic with aid of -1 and iid of -1
> 2023-11-10T06:22:44.606Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP Response is finished
> 2023-11-10T06:22:45.123Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] Client connection closed
> 2023-11-10T06:22:45.124Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> 2023-11-10T06:22:45.124Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP connection was closed
> 2023-11-10T06:22:45.125Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.176] HTTP server was closed
> [11/10/2023, 7:22:46 AM] [homebridge-molekule] ✓ Valid Login Credentials

**Comment by csirikak** [comment]
I think you have node debug mode on but not the homebridge debug mode. 
It should be possible to run homebridge with the debug mode with 
`homebridge -D`
Or if you use the web UI there's a switch in settings.

**Comment by jakubkasparek** [comment]
@csirikak  I'm sorry, but I gave up. And sold the cleaner.

**Comment by jakubkasparek** [comment]
did you fixed, it?
