### ISSUE TITLE
Air mini +

### ISSUE THREAD

**Issue by Mrca3D** [csirikak/homebridge-molekule#13]
Hi,

I installed this plugin, and while it is able to show "Valid Login Credentials", no devices are shown in the home app. I am using an Air mini+. Any way I can fix this?

**Comment by Mrca3D** [comment]
[17/11/2023, 08:19:12] [homebridge-molekule] HTTP GET STATUS: 200

**Comment by csirikak** [comment]
> [17/11/2023, 08:19:12] [homebridge-molekule] HTTP GET STATUS: 200

Can you post the log of homebridge in debug mode so I can see what is the server response?

**Comment by Mrca3D** [comment]
Hello i attached the .txt file. Odesláno z iPhonu21. 11. 2023 v 0:37, Chiripol S. ***@***.***>:﻿

[17/11/2023, 08:19:12] [homebridge-molekule] HTTP GET STATUS: 200

Can you post the log of homebridge in debug mode so I can see what is the server response?

**Comment by csirikak** [comment]
> Hello i attached the .txt file. Odesláno z iPhonu21. 11. 2023 v 0:37, Chiripol S. ***@***.***>:﻿
> 
> 
> 
> [17/11/2023, 08:19:12] [homebridge-molekule] HTTP GET STATUS: 200
> 
> 
> 
> Can you post the log of homebridge in debug mode so I can see what is the server response?
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I can't see your text file unfortunately. Maybe you can do it from the GitHub website.

**Comment by Mrca3D** [comment]
Look at the e-mail I sent it attached.Odesláno z iPhonu21. 11. 2023 v 11:45, Chiripol S. ***@***.***>:﻿

Hello i attached the .txt file. Odesláno z iPhonu21. 11. 2023 v 0:37, Chiripol S. @.***>:﻿
[17/11/2023, 08:19:12] [homebridge-molekule] HTTP GET STATUS: 200
Can you post the log of homebridge in debug mode so I can see what is the server response?
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

I can't see your text file unfortunately. Maybe you can do it from the GitHub website.

**Comment by Mrca3D** [comment]
[homebridge.txt](https://github.com/csirikak/homebridge-molekule/files/13434613/homebridge.txt)

**Comment by jakubkasparek** [comment]
I know of two other air cleaners that are waiting for this error to be fixed.

However, I am afraid that it will be a problem with the API from the molekule, that perhaps it is only blocking traffic from Central Europe.

**Comment by csirikak** [comment]
> [homebridge.txt](https://github.com/csirikak/homebridge-molekule/files/13434613/homebridge.txt)

It seems like you don't even have any devices registered so nothing is being passed via the API. Would you confirm if devices are added in the app on your phone?

**Comment by Mrca3D** [comment]
Yes of course the deviace has been successfully added in the Molekule application and can be controlled in the application without any problems.Odesláno z iPhonu25. 11. 2023 v 5:02, Chiripol S. ***@***.***>:﻿

homebridge.txt

It seems like you don't even have any devices registered so nothing is being passed via the API. Would you confirm if devices are added in the app on your phone?

**Comment by jakubkasparek** [comment]
@csirikak is there technical documentation somewhere for the molecule purifier API? I would like to help.

**Comment by csirikak** [comment]
> @csirikak is there technical documentation somewhere for the molecule purifier API? I would like to help.

There's 0 documentation available. What you can do is to use the an app like [Proxyman](https://apps.apple.com/us/app/proxyman-network-debug-tool/id1551292695) to snoop on requests from the Molekule app. 

You can also clone the repository and make changes. 

Finally, if you're willing, you also can dm me your Molekule credentials and I can try to figure out why you're having issues.
