### ISSUE TITLE
Version 1.4.2 causes Air Pro to send offline status to HomeKit

### ISSUE THREAD

**Issue by vanpatrickbevill** [csirikak/homebridge-molekule#14]
Rolling back to 1.4.1 fixed the issue. Attache logs show child bridge running 1.4.2 with the errors, restart of 1.4.2 with same error after, downgrade to 1.4.1 produces no error and Air Pro is responsive in Apple Home App.
[homebridge-molekule.log.txt](https://github.com/csirikak/homebridge-molekule/files/15017430/homebridge-molekule.log.txt)

**Comment by csirikak** [comment]
Would you run homebridge in debug mode: 
![image](https://github.com/csirikak/homebridge-molekule/assets/32028457/d9c0c209-eb73-4af7-8fe1-758f98681426)
and report the log, especially the section that looks like: `found device from API:`


`found device from API: {"serialNumber":"MN14-SHA190919-004832","name":"MOLEKULE_4832","subProduct":{"id":1,"name":"Air Mini Basic","product":{"id":4,"name":"MN","description":"Molekule Air mini","serialNumberPrefix":"MN","health":["sn","fw","mid"]},"createdBy":"admin-app@molekule.com","createdAt":"2020-03-18T12:11:58.462Z","updatedBy":"admin-app@molekule.com","updatedAt":"2020-03-18T12:11:58.462Z","serialNumberPrefix":"MN1"},"firmwareVersion":"9.4.32.1","model":"Air Mini Basic","firstConnectedUser":"55ea56c1-b9ae-46ff-9bba-0e67118896ed","firstConnectionDate":"2024-03-11T04:31:28.703Z","macAddress":"10:8E:BA:00:1E:98","pecoFilter":"90","fanspeed":"3","mode":"off","online":"false","aqi":"not determined","silent":"","burst":"0"}`

**Comment by vanpatrickbevill** [comment]
Sure thing! Can you clarify two things for me: 1) I assume you want me to reinstall 1.4.2- just checking ;) and 2) you want me to use the environment variable leap:* as shown in your screenshot? I've never run debug mode before so this should be fun!

**Comment by csirikak** [comment]
> Sure thing! Can you clarify two things for me: 1) I assume you want me to reinstall 1.4.2- just checking ;) and 2) you want me to use the environment variable leap:* as shown in your screenshot? I've never run debug mode before so this should be fun!

- Can you choose the version `v1.4.2-alpha`
- You can omit the environment variable this time

**Comment by vanpatrickbevill** [comment]
I no longer receive the error with 1.4.2-alpha. Here are the verbose logs just in case you need them.

Thanks for the amazingly quick responses!

[homebridge-molekule.log-3.txt](https://github.com/csirikak/homebridge-molekule/files/15018501/homebridge-molekule.log-3.txt)
