### ISSUE TITLE
Air Quality Reporting

### ISSUE THREAD

**Issue by csirikak** [csirikak/homebridge-molekule#6]
### The Molekule Air Pro and Basic+ has a AQI reporting function.

- https://api.molekule.com/users/me/devices?size=100 reports a key: `aqi` with a string value assumed to use the following values: `good`, `moderate`, `bad`, `very bad` according to app screenshots.
- homekit also includes a mechanism for reporting VOC, PM2.5, PM10, however the API call needed to access this information from Molekule is unknown.

### How you can help

- Use [proxyman](https://apps.apple.com/us/app/proxyman/id1551292695) and navigate the "Indoor Air" tab in the molekule app if you have an air pro.
- Test alpha and beta versions, and report issues.
- [Redact tokens from your proxyman log](https://gist.github.com/csirikak/28df6bf207b95590c4fd2e080676367b)

**Comment by QandnotU** [comment]
Let me know if this did the trick.

[api.molekule.com_09-02-2023-18-48-07.proxymanlogv2.zip](https://github.com/csirikak/homebridge-molekule/files/12505013/api.molekule.com_09-02-2023-18-48-07.proxymanlogv2.zip)

**Comment by csirikak** [comment]
### Version `1.4.0-alpha` now includes AQI reporting

- The air quality is included as one device in the home app along with the purifier
- the method `sensordata` does not accept cognito auth tokens, must use ID token instead
- `sensordata` must be queried with a from and to date, range is set to 60 minutes
- the plugin takes the most recent nonnegative values and passes it to homebridge

- fixes for problems in #5

**Comment by QandnotU** [comment]
@csirikak thank you sir.

I'm not seeing 1.4.0 in my list, if you wouldn't mind putting it up, I'll put it through its paces, and again, thank you again for all your work on this.

**Comment by QandnotU** [comment]
1.3.6

- Air Pro still experiencing an error when switching from Manual to Auto.
- Not sure if this the additional AQI reporting was in this build, but only seeing Air Quality.

**Comment by QandnotU** [comment]
Since you don't have the hardware, I thought you might want to see how these additional AQIs are appearing in the Home app.

Mini+
![IMG_1946](https://github.com/csirikak/homebridge-molekule/assets/1828180/a4f3a210-581b-44c5-ab84-3856c30a033c)
Air Pro
![IMG_1947](https://github.com/csirikak/homebridge-molekule/assets/1828180/650f7c63-3797-46e0-8858-54a891d20a11)

**Comment by csirikak** [comment]
> Since you don't have the hardware, I thought you might want to see how these additional AQIs are appearing in the Home app.

Thanks, I was wondering if it would be better to include the sensors as a separate accessory. Also, is the data accessible from automations?

**Comment by QandnotU** [comment]
I seem to be able to conditionally fire automatons based on a AQI characteristic without it being a separate accessory.

![IMG_1950](https://github.com/csirikak/homebridge-molekule/assets/1828180/9c86e662-81bb-4188-bfe5-d2fa75c6da58)

With that said, if I look at another purifier, it is a separate accessory, allowing the attribute to be shown in the header overview. Currently that's not showing with the Molekule.

![IMG_1948](https://github.com/csirikak/homebridge-molekule/assets/1828180/17ed4045-da61-47be-a9c0-91412c9f6613)

**Comment by csirikak** [comment]
v1.4.1 adds the option to report aqi and humidity as a separate accessory. This allows the info to show up in the home overview

**Comment by QandnotU** [comment]
@csirikak everything looks and is working great! Thank you again for your work on this, its nice to have a proper plugin for these overpriced purifiers :)

**Comment by csirikak** [comment]
If you notice any other issues please let me know, I'll be happy to work on them.
